root: true
env:
  browser: true
  es6: true
  webextensions: true
parserOptions:
  ecmaVersion: 10
plugins:
  - prettier
rules:
  prettier/prettier: error
extends:
  - eslint:recommended
  - prettier
